Model morphism validation
ToposInstitute/CatColab pull request #155
Opened 2024-09-07 02:43 UTC by kris-brown

Addresses https://github.com/ToposInstitute/CatColab/issues/104

This PR defines a `DblModelMorphism` type which contains a double model mapping as well as info about the domain and codomain. This can be validated to see if objects/generating morphisms are not mapped at all, mapped to invalid identifiers, mapped to things of the wrong type, or mapped in a way that doesn't preserve dom/codom (for the morphisms).

2024-09-07 03:05 UTC, epatters commented
Thanks Kris! One quick comment: to fix the CI failure, run the linter (`cargo clippy`).

2024-09-10 03:05 UTC, epatters requested changes
Thanks Kris, this is great! I left a few comments.

2024-09-10 03:05 UTC, epatters commented on packages/catlog/src/dbl/model_morphism.rs
> +use crate::validate::{self, Validate};
I like to separate the `crate` imports from the external ones, hence this import would go below. Unfortunately the linter is not smart enough to this automatically.

2024-09-10 03:05 UTC, epatters commented on packages/catlog/src/dbl/model_morphism.rs
> +    Dom::MorGen: Clone,
Hopefully with #138 it is possible to remove these two bounds.

2024-09-10 03:05 UTC, epatters commented on packages/catlog/src/dbl/model_morphism.rs
> +    Dom::MorGen: Clone,
Ditto.

2024-09-10 03:05 UTC, epatters commented on packages/catlog/src/dbl/model_morphism.rs
> +    Ob(Ob),
With the recent factor #118, we are now properly distinguishing objects/morphisms from object/morphisms *generators* in the traits for finitely generated categories and models. Mappings between double models are defined on object/morphism generators and take values in objects/morphisms. Given that, I think this enum should have signature

```rust
pub enum InvalidDblModelMorphism<ObGen, MorGen> 
```

As a side benefit, this should clean up the validation code because you'll have to write `.into()` a lot less often.

2024-09-10 03:05 UTC, epatters commented on packages/catlog/src/dbl/model_morphism.rs
> +    use std::collections::HashMap;
Ditto the organization of imports here.

2024-09-10 03:05 UTC, epatters commented on packages/catlog/src/dbl/model_morphism.rs
> +        };
Not essential but perhaps worth adding a `new` method to `DiscreteDblModelMapping` that takes two hash maps as its arguments.

2024-09-10 03:05 UTC, epatters commented on packages/catlog/src/dbl/model_morphism.rs
> +    fn validate_model_morphism() {
Thanks so much for thorough tests!

2024-09-10 03:05 UTC, epatters commented on packages/catlog/src/dbl/model_morphism.rs
> +        let bad_ob_assign: HashMap<ustr::Ustr, Ustr> =
You should be able to save a few characters here and below by writing `HashMap<_, _>`.

2024-09-10 19:25 UTC, kris-brown commented on packages/catlog/src/dbl/model_morphism.rs
> +    Dom::MorGen: Clone,
To my surprise, it wasn't possible to remove these bounds without adding `Eq+Clone` here:

```rust 
pub trait FgCategory: Category {
    /// The type of object generators.
    type ObGen: Eq + Clone + Into<Self::Ob>;

    /// The type of morphism generators. Often Mor = Path<Ob, MorGen>.
    type MorGen: Eq + Clone + Into<Self::Mor>;
```

Which was not part of #138

2024-09-10 21:55 UTC, epatters commented on packages/catlog/src/dbl/model_morphism.rs
> +    Dom::MorGen: Clone,
Yep, I think that's just a spot we missed in #138.

2024-09-10 22:37 UTC, merged